version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    working_directory: ~/src
    executor: python/default
    steps:
      - checkout
      - run:
            name: 'Install project dependencies'
            command: |
              sudo pip install pipenv
              pipenv install
